[build-system]
requires = [
  "setuptools>=41.2",
  "setuptools-scm",
  "cython>=3",
  "numpy>=2",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "ciso"
dynamic = ["version"]
description = "Create isosurfaces from 2D or 3D arrays"
readme = "README.md"
authors = [
  {email = "hetland@tamu.edu"},
  {name = "Robert Hetland"}
]
requires-python = ">=3.11"
license = {text = "BSD-2-Clause"}
dependencies = [
    "numpy",
]

[dependency-groups]
dev = [
  "prek",
  "pytest",
]
docs = [
  "cartopy",
  "gridgeo>=1.6.0",
  "nbconvert>=7.16.6",
  "nbsphinx",
  "pooch",
  "scitools-iris>=3.9.0",
  "xarray",
  # "notebook>=7.4.4"
  { include-group = "dev" },
]

[project.urls]
homepage = "https://github.com/ioos/ciso"
documentation = "https://ioos.github.io/ciso"
repository = "https://github.com/ioos/ciso"

[tool.setuptools]
license-files = ["LICENSE.txt"]
zip-safe = true
platforms = ["any"]
packages = ["ciso"]

[tool.setuptools_scm]
write_to = "ciso/_version.py"
write_to_template = "__version__ = '{version}'"
tag_regex = "^(?P<prefix>v)?(?P<version>[^\\+]+)(?P<suffix>.*)?$"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::UserWarning",
]
addopts = "-s -rxs -v"

[check-manifest]
ignore = [
    "*.yml",
    ".coveragerc",
    "docs",
    "docs/*",
    "notebooks",
    "notebooks/*",
    "tests",
    "tests/*",
]

# pre-commit = "pre-commit run --all-files"
